name: Generate and Push Sitemap

on:
  push:
    branches: ["main"] # اگر اسم برنچ اصلی‌ت master هست، این رو بکن master

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Create Sitemap Manually
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          # پیدا کردن تمام فایل‌های html و ساخت تگ‌های loc
          find . -name "*.html" ! -name "404.html" -not -path '*/.*' | sed 's|^\./||' | sed "s|^|  <url><loc>https://dentcast.ir/|" | sed "s|$|</loc></url>|" >> sitemap.xml
          echo '</urlset>' >> sitemap.xml
          echo "ساختار فایل سیت‌مپ ساخته شده:"
          cat sitemap.xml
          echo "لیست فایل‌های موجود در پوشه:"
          ls -lh sitemap.xml

      - name: 3. Install AWS CLI
        run: |
          python3 -m pip install --upgrade pip
          pip install awscli

      - name: 4. Upload Sitemap to Arvan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ARVAN_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARVAN_SECRET_KEY }}
          AWS_EC2_METADATA_DISABLED: "true"
          ARVAN_BUCKET: ${{ secrets.ARVAN_BUCKET }}
          ARVAN_ENDPOINT: ${{ secrets.ARVAN_ENDPOINT }}
        run: |
          # آپلود تک فایل سیت‌مپ با دسترسی عمومی
          aws s3 cp sitemap.xml "s3://$ARVAN_BUCKET/sitemap.xml" \
            --endpoint-url "$ARVAN_ENDPOINT" \
            --acl public-read

      - name: 5. Ping Google
        run: |
          curl "https://www.google.com/ping?sitemap=https://dentcast.ir/sitemap.xml"